@startuml washing machine
' left to right direction

/'
①洗濯物を入れて洗剤をセットし、スタートボタンを押す
②水道につながっているバルブを開き、給水を開始する
③決められた水量が洗濯槽にたまったらバルブを閉じる
④洗濯処理用のモーターを始動させる
⑤設定された洗濯時間が経過したらモーターを止める
⑥排水溝につながっているバルブを開き、排水する
⑦排水完了後にバルブを閉じる
⑧再度給水を開始し、設定された水量に達したらバルブを閉じる
⑨モーターを再度始動させ、すすぎ処理を開始する
⑩設定されたすすぎ時間が経過したらモーターを止める
⑪排水溝につながっているバルブを開いて排水開始
⑫排水完了後にバルブを閉じる
⑬モーターを再度始動させ、給水しながらすすぎ処理（2回目）を行う
⑭排水溝につながっているバルブを開いて排水開始
⑮排水完了後にバルブを閉じる
⑯モーターを始動させ、脱水処理を行う
⑰設定された時間が経過したら脱水完了。モーターを停止させる
⑱終了音を鳴らして洗濯完了
'/

[*] --> スタート指示待機

state 洗濯中 {
    スタート指示待機 --> 洗濯_給水中 : スタートボタンが押下される
    洗濯_給水中 --> 洗濯_洗濯槽回転中 : 水位センサーが一定値を検知した
    洗濯_洗濯槽回転中 --> 洗濯_排水中 : 一定時間経過した

    洗濯_給水中 : entry / 給水弁を開放する
    洗濯_給水中 : exit / 給水弁を閉鎖する
    洗濯_洗濯槽回転中 : entry / 洗濯槽の回転を開始する
    洗濯_洗濯槽回転中 : exit / 洗濯槽の回転を停止する
    洗濯_排水中 : entry / 排水弁を開放する
    洗濯_排水中 : exit / 排水弁を閉鎖する

}

洗濯中 --> 洗濯_停止中 : 蓋が開いた
洗濯_停止中 -left-> 洗濯中[H] : 蓋が閉じた

state すすぎ中 {
    洗濯_排水中 --> すすぎ_給水中 : 水位センサーが一定値を検知した
    すすぎ_給水中 --> すすぎ_洗濯槽回転中 : 水位センサーが一定値を検知した
    すすぎ_洗濯槽回転中 --> すすぎ_排水中 : 一定時間経過した

    すすぎ_給水中 : entry / 給水弁を開放する
    すすぎ_給水中 : exit / 給水弁を閉鎖する
    すすぎ_洗濯槽回転中 : entry / 洗濯槽の回転を開始する
    すすぎ_洗濯槽回転中 : exit / 洗濯槽の回転を停止する
    すすぎ_排水中 : entry / 排水弁を開放する
    すすぎ_排水中 : exit / 排水弁を閉鎖する
}

すすぎ中 --> すすぎ_停止中 : 蓋が開いた
すすぎ_停止中 -left-> すすぎ中[H] : 蓋が閉じた

すすぎ_排水中 --> 脱水中 : 水位センサーが一定値を検知した
脱水中 --> [*] : 一定時間経過 / 終了音を鳴らす

脱水中 -> 脱水_停止中 : 蓋が開いた
脱水_停止中 -left-> 脱水中 : 蓋が閉じた

脱水中 : entry / 洗濯槽の回転を開始する
脱水中 : exit / 洗濯槽の回転を停止する


}
@enduml
