@startuml ExpressSystem
skinparam packageStyle rect
left to right direction

note "アクター目線" as N1

actor 依頼人
actor 集配担当者
actor 受取人

rectangle 自動搬送システム {
集配担当者 -- (収集を指示する)
集配担当者 -- (荷物を依頼する)
(荷物を依頼する) ..> (引き継ぎする) : include
依頼人 -- (荷物を依頼する)
受取人 -- (荷物を受け取る)
}

' 順番整理
集配担当者 .[hidden] 依頼人
(収集を指示する) .[hidden] (荷物を依頼する)
(荷物を依頼する) .[hidden] (荷物を受け取る)

@enduml
