@startuml ExpressSystem
skinparam packageStyle rect
left to right direction

note "システム目線" as note

actor 依頼人
actor 集配担当者
actor 受取人

rectangle 自動搬送システム as system {
    集配担当者 -- (収集する)
    note right of (収集する) : 収集指示～依頼先到着まで

    集配担当者 -- (配達する)
    (配達する) ..> (引き継ぎする) : include

    依頼人 -- (配達する)
    note right of (配達する) : 荷物依頼～受取先到着まで

    受取人 -- (帰還する)
    note right of (帰還する) : 荷物受取り～集配センター到着まで
}

' 順番整理
集配担当者 .[hidden] 依頼人
(収集する) .[hidden] (配達する)
(配達する) .[hidden] (帰還する)

@enduml
